### ISSUE TITLE
Let merchant pass in arbitrary data to payment request?

### ISSUE THREAD

**Issue by zkoch** [WICG/paymentrequest#11]
Should we give merchants the ability to pass in arbitrary data into the payment request? This would be an opaque value to the system and would be passed back to the merchant in the response from UA. An example of this might be a shopping cart session ID.

**Comment by mattsaxon** [comment]
We need at least an TransactionID (or ShoppingCartID), but beyond that I am unsure, this shouldn't become a means of storing state which the merchant already has associated with this ID IMO, however it may become relevant when  this arbitrary data needs to be passed to a PSP and not via the merchant or at least in an encrypted envelope. I expect the Flow Task force to uncover these scenarios.

**Comment by adrianba** [comment]
For now we don't think there needs to be a payment method independent way of passing this data to the user agent. For example, the basic card payment method that returns PANs and expiry, etc. will not need a transaction ID. How this data is handled will vary by payment method and what formats are supported will likely vary (JSON structured data vs. string, for example).

We propose that we handle this by providing any additional data that a payment method knows how to process as part of the payment specific data object that is passed into the `PaymentRequest` constructor. Once we have some implementation experience we can determine if we need to return to this topic and provide a more general way of supplying the data as part of the `PaymentDetails` object.
