### ISSUE TITLE
How do we think it will work with ServiceWorker?

### ISSUE THREAD

**Issue by greenido** [WICG/paymentrequest#12]
In other words, we are moving (fast) into a new world on the web. It will be good to think how this process is going to leverage the capabilities of SW (e.g. offline and/or sync options) when coming to deal with payments.

**Comment by zkoch** [comment]
I can see SW playing a critical role in these flows, especially in emerging markets. A few thoughts, in no particular order:

1.) Offline payments make more sense in COD types of situations (which are more common in India, for example). Money isn't exchanged immediately, so there's no need for immediate settlements. SW could be very useful here.

2.) SW might become necessary if we start talking about interacting with native applications as payment instruments. This becomes particularly relevant on low-memory devices where the potential for the opened web page to become RAM-swapped out is more likely. These merchants would probably need to have a SW component that could deal with this situation (similar to what is being proposed in [ballista](https://github.com/chromium/ballista/blob/master/docs/explainer.md).

3.) SWs are kind of new and scary, so I would be very hesitant about making them a critical part of the system. Merchant adoption is important, and I could see mandatory SW usage as a substantial impediment to adoption. We have to strike the right balance between doing what's best for the web in the long term and what's going to help solve immediate pain points.

**Comment by adrianba** [comment]
After discussing with @zkoch, we're going to close this issue for now with the following resolution:

SW can help solve some particularly challenging cases, but we should not hinge any work for v1 on this. The main flow we have now expects to have some visible user interaction and it’s not yet clear how this might interact with SW. We will revisit the SW topic in a future iteration once we have handled the core use cases.
