### ISSUE TITLE
Could we design appropriate declarative models to go along with the API?

### ISSUE THREAD

**Issue by halindrome** [WICG/paymentrequest#13]
APIs are the right way to start when defining new user agent capabilities.  For the case where the user agent is a "browser", it would also be good to potentially expose the functionality via markup.  It may not be something for V1, but potentially for a V1.1 or V2.

**Comment by adrianba** [comment]
For v1, we're focusing on an imperative API. Experimentation for a declarative model could happen using Web Components. If somebody wants to write a declarative model proposal that maps to Payment Request that would be interesting to review but, for now, we're not going to pursue this.

Closing for now with the future label.
