### ISSUE TITLE
Payment methods registering to handle schemes / Interledger support (in the future)

### ISSUE THREAD

**Issue by emschwartz** [WICG/paymentrequest#14]
It seems like the best way to support something like [Interledger](https://interledger.org) in the future would be to enable payment methods to register to handle schemes not tied to their domains. A payment method like PayPal could register to handle Interledger akin to how it might register to handle card schemes.

Having payment methods register to handle other schemes isn't included in the current proposal, but I would argue it'll be an important function to support.

**Comment by adrianba** [comment]
With the new [Web Payments WG definitions](https://github.com/w3c/webpayments/wiki/A-Payments-Initiation-Architecture-for-the-Web#user-content-definitions) the model appears to support your request: multiple different payment apps might support the same payment method. It will likely be up to the user agent to mediate between the different apps. Presumably the [registration flow for a payment app](http://wicg.github.io/paymentrequest/specs/architecture.html#payment-method-registration-specifications) would include which payment method identifiers it supports.

**Comment by adrianba** [comment]
Closing this issue. Please reopen with new information if this is still a problem once we make more progress on the registration spec (see issue #27).
