### ISSUE TITLE
There should be a way for the merchant to indicate the instrumentResponse was a failure

### ISSUE THREAD

**Issue by halindrome** [WICG/paymentrequest#15]
There is no way in the current design to have the payment be declined.  We need this.

**Comment by adrianba** [comment]
Why would the promise ever complete with a failure? Surely if the UA can determine that payment was declined it would ask the user to try another payment instrument?

**Comment by halindrome** [comment]
Maybe. If they have one. And surely there could be other exceptions.  Like
a timeout. Or the inventory runs out. Or...  Who knows?

**Comment by adrianba** [comment]
Most of these things can occur at any time, though. Like when the fork lift accidently runs over the package and it was the last one in stock.

The current API proposal tries to simplify the "I want to order" step and not the whole supply chain. It's currently up to the web site to decide what to do after the user pushes the pay button based on their backend.
