### ISSUE TITLE
Merchant requesting arbitrary data from the UA

### ISSUE THREAD

**Issue by halindrome** [WICG/paymentrequest#16]
There is a concept that the merchant can request / be informed of a shipping address.  I think the merchant needs to be able to request many things from the UA.  The UA needs to then be able to decide which of those things it knows about, which of them to provide, etc.  Examples include:

Billing Address
Shipping Address
Contact Phone
Proof of Age

Only dealing with shippingAddress is overly simplistic.  Also this might be beyond the scope and we should just leave a hook for this and hand it off to the Credentials work.

**Comment by adrianba** [comment]
This issue is now tracked at w3c/browser-payment-api#1.
