### ISSUE TITLE
UI for Payment Instrument

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#17]
Whilst we are not defining user interfaces standards, I think we need to consider the following;

What is the expectation for the Payment Instrument's UI? Is the expectation that the browser launches the URI in a hidden window and that the payment instrument can launch others?

Has it been considered if a status windows will be needed somewhere in the main UI to keep the shopper aware of the progress, e.g. "authorising", "transferring funds", etc.

**Comment by adrianba** [comment]
The general expectation for how the browser interacts with payment apps for showing UI, etc. will be a topic for @zkoch's registration spec (issue #27).

The issue to consider a status message during processing is issue #32.

Please open other new issues for specific UI questions if you have them. It's good to discuss these in specific terms. I think the registration spec will help clarify many expectations.
