### ISSUE TITLE
Currency Specification

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#18]
Providing the amount in cents where the currency is USD is confusing, typically this is done as a decimal e.g. 55.00 or with an additional exponent value (e.g. 2, suggesting where the decimal point is). This avoids confusion for complex or volatile currencies.

**Comment by dlongley** [comment]
We should use a string for the amount to avoid any potential precision issues with JSON parsers. We want the amount in the message to accurately reflect the author's intent, regardless of the currency type or its number of digits.

Providing a digital signature on the request that only verifies after a normalization phase can also help prevent misrepresenting author intent.

**Comment by zkoch** [comment]
I'm okay with strings. I used cents because that's what Stripe uses. Braintree uses strings. I don't have a strong opinion here.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------

----==_mimepart_56491772348af_51433fe467fdb2a0245157
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

I'm okay with strings. I used cents because that's what Stripe uses. Braintree uses strings. I don't have a strong opinion here.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/18#issuecomment-156870651
----==_mimepart_56491772348af_51433fe467fdb2a0245157
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>I'm okay with strings. I used cents because that's what Stripe uses. Braintree uses strings. I don't have a strong opinion here.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-156870651">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHIvwhAWos1iaIGqzAoHdyN0HTRBzks5pGQ7ygaJpZM4GiVWs.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-156870651"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_56491772348af_51433fe467fdb2a0245157--

**Comment by nelsonmenezes** [comment]
If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.

Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?

Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------

----==_mimepart_5649d564e8b6a_7d663fbb1d1152c033216f3
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.

Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?

Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/18#issuecomment-157023643
----==_mimepart_5649d564e8b6a_7d663fbb1d1152c033216f3
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.</p>

<p>Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?</p>

<p>Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-157023643">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHMQFdCUGImKQ1G1THfdKaOe2WzUYks5pGczkgaJpZM4GiVWs.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-157023643"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_5649d564e8b6a_7d663fbb1d1152c033216f3--

**Comment by dlongley** [comment]
> If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.

The value is an arbitrary precision number expressed as a string, not a display value.

> Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?
> 
> Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.

We don't want to build something into the first version of the spec that will be broken for obvious future use cases. Micropayments, stock trading, etc. can all be solved with an arbitrary precision value that is expressed as a string. The spec would make sure to indicate that it is not a display value and implementations would validate properly.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------


----==_mimepart_564a23d73bbe8_788b3f7f1a1d729c48838
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

> If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.

The value is an arbitrary precision number expressed as a string, not a display value.

> Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?
> 
> Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.

We don't want to build something into the first version of the spec that will be broken for obvious future use cases. Micropayments, stock trading, etc. can all be solved with an arbitrary precision value that is expressed as a string. The spec would make sure to indicate that it is not a display value and implementations would validate properly.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/18#issuecomment-157131837
----==_mimepart_564a23d73bbe8_788b3f7f1a1d729c48838
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<blockquote>
<p>If using strings, note that different locales will use different decimal separators (comma vs decimal dot), as well as other possible formatting. This might be confusing if, e.g. a German price string like "567,89" is displayed to an American user.</p>
</blockquote>

<p>The value is an arbitrary precision number expressed as a string, not a display value.</p>

<blockquote>
<p>Javascript uses IEEE 754 64bit numbers, which allow for 15 digits of precision. For the sake of not complicating the spec, I'd say that's "good enough" for the vast majority of use cases that we are trying to address, no?</p>

<p>Extreme precision would only be significant for things like stock trading, but that sort of transactions are, as far as I understand, out of scope here.</p>
</blockquote>

<p>We don't want to build something into the first version of the spec that will be broken for obvious future use cases. Micropayments, stock trading, etc. can all be solved with an arbitrary precision value that is expressed as a string. The spec would make sure to indicate that it is not a display value and implementations would validate properly.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-157131837">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHHVMDsPyXE8PP4Z9QTnWySC_aP7fks5pGhtXgaJpZM4GiVWs.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/18#issuecomment-157131837"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_564a23d73bbe8_788b3f7f1a1d729c48838--
