### ISSUE TITLE
Clarity on Currency Conversion

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#19]
How is matching of payer currency to merchant currency managed in the flow, the flow as shown implies that the visa instrument will have to deal with providing USD, whereas this might not be supported by the card issuer. Who is responsible for doing to exchange or is this an exception?

**Comment by zkoch** [comment]
I think this is an exception. Worst case, the payment app could throw an error of some kind if it isn't supported. Perhaps this is also something we should consider when finding the intersection of supported payment instruments.

**Comment by mountainhippo** [comment]
As things stand today, it is the merchant (actually their acquirer) who determines the currency that is presented for payment. 
In some circumstances, the payer instrument can prompt other currencies to become available (Cardholder Preferred Currency) but this is not necessarily the norm.

**Comment by zkoch** [comment]
Yep, and the current proposal assumes this is the way it is.

**Comment by adrianba** [comment]
This is now tracked at w3c/browser-payment-api#3.
