### ISSUE TITLE
Shipping: should merchant supply supported destinations

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#2]
Merchants frequently have restrictions on where they can ship goods. Should this be passed proactively in some form to allow the UA to not offer unsupported destinations.

**Comment by zkoch** [comment]
Good point. One way I could think of supporting this is to allow for a supportedCountries option in the initial request as an optional parameter. Would that be enough?

Another option would be to actually use the event model that's in the proposal and let the merchant declare that the chosen country is not supported on address change.

**Comment by adrianba** [comment]
> One way I could think of supporting this is to allow for a supportedCountries option in the initial request as an optional parameter. Would that be enough?

We discussed this and had come up with that as a reasonable compromise before I read your response.

> Another option would be to actually use the event model that's in the proposal and let the merchant declare that the chosen country is not supported on address change.

I think we will need this as part of the eventing model. For example, in the US, some merchants can only ship to the lower 48. For others, certain products can't be shipped to certain states. I imagine there are people with all kinds of complex rules.

**Comment by adrianba** [comment]
This is currently defined in the [`PaymentDetails` section](https://wicg.github.io/paymentrequest/specs/paymentrequest.html#paymentdetails-dictionary) where the spec describes the `shippingOption` sequence and says, "If the sequence is empty, then this indicates that the merchant cannot ship to the current `shippingAddress`."
