### ISSUE TITLE
Standardizing Common Payment Instruments

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#20]
Different card schemes have different mandatory requirement, some needing either an Issue number of a Start Date rather than the more common CardNumber (PAN) and Expiry Date. We should acknowledge this in the specification.

**Comment by zkoch** [comment]
+1. Would love any more thoughts you have on this (or if you could point me to a place that has all of these different requirements). Happy to work these in.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------


----==_mimepart_564914e391786_1de63fe467fdb2a01624f4
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

+1. Would love any more thoughts you have on this (or if you could point me to a place that has all of these different requirements). Happy to work these in.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/20#issuecomment-156868875
----==_mimepart_564914e391786_1de63fe467fdb2a01624f4
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>+1. Would love any more thoughts you have on this (or if you could point me to a place that has all of these different requirements). Happy to work these in.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/20#issuecomment-156868875">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHOyuAnBZiQ7S2LLoNy52Mi1i0Am7ks5pGQxjgaJpZM4GiVZ5.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/20#issuecomment-156868875"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_564914e391786_1de63fe467fdb2a01624f4--

**Comment by mattsaxon** [comment]
The Worldpay specification here http://dtd.worldpay.com/v1/ has the various schema defined in the paymentDetails element

**Comment by adrianba** [comment]
I think this is called out in the [architecture document](http://wicg.github.io/paymentrequest/specs/architecture.html#payment-transaction-message-specifications). Each payment method will need to declare which payment transaction message specification it supports.

**Comment by adrianba** [comment]
> Different card schemes have different mandatory requirement, some needing either an Issue number of a Start Date rather than the more common CardNumber (PAN) and Expiry Date. We should acknowledge this in the specification.

I will try to cover this in the card payment method specification in issue #31.

**Comment by adrianba** [comment]
Now tracked by w3c/browser-payment-api#9.
