### ISSUE TITLE
Location of Authorisation in the flow

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#22]
> “5. Payment instrument returns back relevant data (e.g. credit card number, token, transaction ID) after successful authorization or transaction to UA” suggest that the authorisation occurs in the payment instrument”

This paragraph suggests that an authorisation at least is performed, but there is no mechanism for explaining how this occurs for the standard payment instruments. Is this a payment authorisation? Or just authorisation from the payer to use the instrument?

**Comment by zkoch** [comment]
Perhaps it would be more accurate to phrase it as "authorization (if necessary)". Either way, this is up to the payment instrument. Not to the spec.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------


----==_mimepart_564914b14195d_5b263fc92eb9729c202912
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Perhaps it would be more accurate to phrase it as "authorization (if necessary)". Either way, this is up to the payment instrument. Not to the spec.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/22#issuecomment-156868836
----==_mimepart_564914b14195d_5b263fc92eb9729c202912
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Perhaps it would be more accurate to phrase it as "authorization (if necessary)". Either way, this is up to the payment instrument. Not to the spec.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/22#issuecomment-156868836">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHAP07Pq8Is736w6klDAtQqKQTTmCks5pGQwxgaJpZM4GiVcf.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/22#issuecomment-156868836"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_564914b14195d_5b263fc92eb9729c202912--

**Comment by mattsaxon** [comment]
Thanks Zach, I'm happy with that clarification, it makes sense to me.
