### ISSUE TITLE
API needs equivalent of PassKit's paymentAuthorizationViewController:didAuthorizePayment:completion: callback

### ISSUE THREAD

**Issue by hober** [WICG/paymentrequest#23]
Hi,

In PassKit (the Apple Pay API) the payment sheet stays up until the app calls this completion handler with either `PKPaymentAuthorizationStatus.Success` or `PKPaymentAuthorizationStatus.Failure`. (You can read more about this in the [official docs](https://developer.apple.com/library/ios/documentation/PassKit/Reference/PKPaymentAuthorizationViewControllerDelegate_Ref/index.html#//apple_ref/doc/c_ref/PKPaymentAuthorizationStatus), although you might find [this NSHipster blog post](http://nshipster.com/apple-pay/#pkpaymentauthorizationviewcontrollerdelegate) to be more straightforward.)

In order for this JS API to work with PassKit, the UA needs to expose a method that the merchant calls to signify success or failure after it does whatever it does with the instrumentResponse.

**Comment by hober** [comment]
This may be a duplicate of #15; if so, please take this as new information for that issue.

**Comment by zkoch** [comment]
Thanks for bringing this up. I'm not quite sure how the spec should handle this case. From an API perspective, it's quite simple. The final `instrumentResponse` object could have a function that the merchant could call that passes arbitrary information back to the payment app. e.g.

```js
.then(function(instrumentResponse){
  instrumentResponse.onCompletion(...);
});
```

The tricky part is figuring out how that works across different platforms. How does the UA pass the data back to the payment instrument? Would we need some way in the request to let merchants know that calling this function is required, or would this just be something that the merchant would have to know as part of accepting apple pay for example? My hunch is the latter, but need to think more. Do you have other thoughts on API design here?

**Comment by hober** [comment]
I don't see why the call would be optional. The UA needs to know when it can dismiss the sheet.

**Comment by zkoch** [comment]
Well, I think in most cases the UI can be dismissed after an instrumentResponse is received. Apple Pay and Android Pay are rare cases where there is an additional call to indicate success or failure.

**Comment by marcoscaceres** [comment]
> Well, I think in most cases the UI can be dismissed after an instrumentResponse is received. Apple Pay and Android Pay are rare cases where there is an additional call to indicate success or failure.

I'm not sure we can say "Apple Pay and Android Pay are rare cases", when they are the primary targets for this API. From Mozilla's perspective, these APIs MUST work well primarily with iOS and Android.

**Comment by hober** [comment]
I completely agree with what Marcos just said.

**Comment by zkoch** [comment]
I think they are one of the targets for this API, but they are not the only payment apps we can or should care about supporting with this API.

That said, I agree that if this is critical it should be included in the API. I think the complexities I mentioned are still present, so would appreciate more thoughts if people have them.

**Comment by adrianhopebailie** [comment]
>Would we need some way in the request to let merchants know that calling this function is required, or would this just be something that the merchant would have to know as part of accepting apple pay for example? My hunch is the latter, but need to think more.

We have talked about the API accommodating a flag in the request that indicates to the payment instrument that there will be a second message from the Website either requesting that the payment should be completed (in the case of a credit push payment) or a notification of the status of the transaction.

Others have proposed that payment instruments [1] should deal with this out of band. i.e. The payment instrument returns a callback URL to the Website and it sends the completion message to that URL after the PSP has processed the payment.

It would be very useful if someone could capture the ApplePay flow in a flow diagram in the same way as others have been captured already [here](https://github.com/w3c/webpayments/tree/gh-pages/PaymentFlows). The WG will use these as the mechanism to ensure the API accommodates existing use cases.

[1] We're tending toward using more developer friendly language that isn't loaded with existing definitions and calling payment instruments, [payment apps](https://github.com/w3c/webpayments/wiki/A-Payments-Initiation-Architecture-for-the-Web))
