### ISSUE TITLE
Price breakdown

### ISSUE THREAD

**Issue by jayrenn** [WICG/paymentrequest#25]
Most merchants break down their final price into separate line items, such as subtotal, sales tax, shipping cost, total, etc. Currently, the spec only requests one number, `amount`.

For what it's worth, Apple Pay uses an [array of summary items](https://developer.apple.com/library/ios/ApplePay_Guide/CreateRequest.html#//apple_ref/doc/uid/TP40014764-CH3-SW1), where the developer is responsible for totaling up the final price. The shipping method is treated as a [special summary item](https://developer.apple.com/library/ios/ApplePay_Guide/CreateRequest.html#//apple_ref/doc/uid/TP40014764-CH3-SW5), and the last summary item is reserved for the grand total.

**Comment by adrianba** [comment]
We've discussed this and I will write-up a proposal for including an array of items in the PaymentDetails and integrating a method for the page to update the price, for example when shipping address changes.
