### ISSUE TITLE
Write-up proposal for shipping address fields

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#28]
@rsolomakhin has researched this area and is going to make a proposal.

**Comment by rsolomakhin** [comment]
I propose the following shipping address schema.

 ```WebIDL
 interface ShippingAddress {
    // CLDR (Common Locale Data Repository) region code.
    readonly attribute DOMString regionCode;

    // The address lines represent the most specific part of any address.
    readonly attribute sequence<DOMString> addressLine;

    // Top-level administrative subdivision of this country.
    readonly attribute DOMString administrativeArea;

    // Generally refers to the city/town portion of an address.
    readonly attribute DOMString locality;

    // Dependent locality or sublocality. Used for UK dependent localities, or
    // neighborhoods or boroughs in other locations.
    readonly attribute DOMString dependentLocality;

    // Values are frequently alphanumeric.
    readonly attribute DOMString postalCode;

    // This corresponds to the SortingCode sub-element of the xAL
    // PostalServiceElements element. Use is very country-specific.
    readonly attribute DOMString sortingCode;

    // Language code of the address. Should be in BCP-47 format.
    readonly attribute DOMString languageCode;

    // The organization, firm, company, or institution at this address. This
    // corresponds to the FirmName sub-element of the xAL FirmType element.
    readonly attribute DOMString organization;

    // Name of recipient or contact person. Not present in xAL.
    readonly attribute DOMString recipient;
};
```

This is based on [libaddressinput](https://github.com/googlei18n/libaddressinput/), which Chrome uses internally for autofill. In particular, these fields come from [address_data.h](https://github.com/googlei18n/libaddressinput/blob/master/cpp/include/libaddressinput/address_data.h). The field names correspond to the [OASIS xAL standard](https://www.oasis-open.org/committees/ciq/download.shtml).

This may not be The Best (tm) addressing schema overall, but a good start. I welcome discussion on this topic.

**Comment by dlongley** [comment]
Something to consider: http://schema.org/PostalAddress

**Comment by rsolomakhin** [comment]
@dlongley , thank you. Indeed there are very many things to consider:

 - http://microformats.org/wiki/adr
 - https://www.easypost.com/docs/api#addresses
 - https://developer.visa.com/vme/merchant/documents/Client_API_Reference/xml/Consumer_Information.html
 - https://developer.authorize.net/api/reference/
 - http://apps.cybersource.com/library/documentation/dev_guides/VCO_SO_API/Visa_Checkout_SO_API.pdf
 - https://developers.google.com/android/reference/com/google/android/gms/identity/intents/model/UserAddress
 - https://developer.apple.com/library/prerelease/ios/documentation/Contacts/Reference/CNMutablePostalAddress_Class/
 - https://developer.paypal.com/docs/api/#creditcard-object
 - https://stripe.com/docs/api/java#card_object
 - https://online.worldpay.com/api-reference#orders
 - https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US
 - https://www.usps.com/business/web-tools-apis/international-shipping-label-api.htm
 - https://developers.google.com/maps/documentation/geocoding/intro#Types

These agree very rarely.

**Comment by dlongley** [comment]
Being able to map these fields to global identifiers (URIs) helps solve that problem.

**Comment by webpayments** [comment]
Sure - but in terms of eating our own dogfood, and scalability and
extensibility, relying upon the schema.org semantics and its
follow-your-nose nature gives us a strong basis.  I personally think we
should be using schema.org (or other RDF-y vocabuaries) for everything we
can!

On Mon, Feb 22, 2016 at 1:37 PM, Rouslan Solomakhin <
notifications@github.com> wrote:

> @dlongley <https://github.com/dlongley> , thank you. Indeed there are
> very many things to consider:
>
>    - http://microformats.org/wiki/adr
>    - https://www.easypost.com/docs/api#addresses
>    -
>    https://developer.visa.com/vme/merchant/documents/Client_API_Reference/xml/Consumer_Information.html
>    - https://developer.authorize.net/api/reference/
>    -
>    http://apps.cybersource.com/library/documentation/dev_guides/VCO_SO_API/Visa_Checkout_SO_API.pdf
>    -
>    https://developers.google.com/android/reference/com/google/android/gms/identity/intents/model/UserAddress
>    -
>    https://developer.apple.com/library/prerelease/ios/documentation/Contacts/Reference/CNMutablePostalAddress_Class/
>    - https://developer.paypal.com/docs/api/#creditcard-object
>    - https://stripe.com/docs/api/java#card_object
>    - https://online.worldpay.com/api-reference#orders
>    - https://www.ups.com/upsdeveloperkit/downloadresource?loc=en_US
>    -
>    https://www.usps.com/business/web-tools-apis/international-shipping-label-api.htm
>    -
>    https://developers.google.com/maps/documentation/geocoding/intro#Types
>
> These agree very rarely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-187397237>.
>



-- 
-Shane

**Comment by rsolomakhin** [comment]
I'm OK with schema.org/PostalAddress, if it's possible to express it in WebIDL form for a spec. Although it's very Western centric, so are many of the financial and shipping APIs.

@dlongley , please propose a WebIDL form for schema.org/PostalAddress.

Keep in mind that schema.org is not set in stone. It's hosted on github and accepts pull requests. If we need to change it, it should be possible in theory.

**Comment by webpayments** [comment]
You're right that it is not set in stone - which is great.  I have been
looking at the schema.org definitions... and I wonder if
http://schema.org/ParcelDelivery might be more appropriate than
http://schema.org/PostalAddress

ParcelDelivery is a specialization designed for actually shipping.

On Mon, Feb 22, 2016 at 1:48 PM, Rouslan Solomakhin <
notifications@github.com> wrote:

> I'm OK with schema.org/PostalAddress, if it's possible to express it in
> WebIDL form for a spec. Although it's very Western centric, so are many of
> the financial and shipping APIs.
>
> @dlongley <https://github.com/dlongley> , please propose a WebIDL form
> for schema.org/PostalAddress.
>
> Keep in mind that schema.org is not set in stone. It's hosted on github
> and accepts pull requests. If we need to change it, it should be possible
> in theory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-187401455>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by webpayments** [comment]
Never mind - I take that back.  It is too intertwined with things like
invoices and receipts.  That's a can of worms that I don't think we want to
open right now.

On Mon, Feb 22, 2016 at 4:56 PM, Shane McCarron <shane@spec-ops.io> wrote:

> You're right that it is not set in stone - which is great.  I have been
> looking at the schema.org definitions... and I wonder if
> http://schema.org/ParcelDelivery might be more appropriate than
> http://schema.org/PostalAddress
>
> ParcelDelivery is a specialization designed for actually shipping.
>
> On Mon, Feb 22, 2016 at 1:48 PM, Rouslan Solomakhin <
> notifications@github.com> wrote:
>
>> I'm OK with schema.org/PostalAddress, if it's possible to express it in
>> WebIDL form for a spec. Although it's very Western centric, so are many of
>> the financial and shipping APIs.
>>
>> @dlongley <https://github.com/dlongley> , please propose a WebIDL form
>> for schema.org/PostalAddress.
>>
>> Keep in mind that schema.org is not set in stone. It's hosted on github
>> and accepts pull requests. If we need to change it, it should be possible
>> in theory.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-187401455>
>> .
>>
>
>
>
> --
> Shane McCarron
> Projects Manager, Spec-Ops
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by nickjshearer** [comment]
The current schema.org/PostalAddress is not suitable as-is, it's missing several fields that are required in certain countries so would have to be modified (per Rouslan's comment, it's very western centric). I am happy with OASIS xAL.

**Comment by webpayments** [comment]
I agree that PostalAddress is missing things.  It would be nice to help
them fix it - but clearly that is something for another thread!

I will look at the (full) OASIS xAL.  My instinct here is to try to rely
upon existing standards as much as possible.  And prefer local standards
when they exist.  Hence my preference for trying to use schema.org for
vocabulary items whenever we can.  They are playing at the W3C so we should
play with them.

On Mon, Feb 22, 2016 at 5:04 PM, Nick S <notifications@github.com> wrote:

> The current schema.org/PostalAddress is not suitable as-is, it's missing
> several fields that are required in certain countries so would have to be
> modified (per Rouslan's comment, it's very western centric). I am happy
> with OASIS xAL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-187460019>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by rsolomakhin** [comment]
Shane, beware that the full OASIS xAL is huge.

**Comment by webpayments** [comment]
Yep - reading it now.

On Mon, Feb 22, 2016 at 5:56 PM, Rouslan Solomakhin <
notifications@github.com> wrote:

> Shane, beware that the full OASIS xAL is huge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-187477009>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by mountielee** [comment]
need to read IETF ECML https://www.ietf.org/rfc/rfc3106
touching address format.

**Comment by webpayments** [comment]
Also the Oasis xAL schema (instance at http://shane.spec-ops.io/xAL/xAL.html)
and the worldpay DTD (instance at http://dtd.worldpay.com/v1/)

On Wed, Feb 24, 2016 at 3:12 PM, Mountie Lee <notifications@github.com>
wrote:

> need to read IETF ECML https://www.ietf.org/rfc/rfc3106
> touching address format.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-188506108>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by burdges** [comment]
Just an aside, we know that shipping address cannot be divulged without user interaction, but presumably the amount of user interaction is quite significant, as people use numerous shipping addresses, and the option for these things are quite significant.  We're therefore talking about something more than a browser pop up every time a person wants to submit a shipping address, yes?

**Comment by webpayments** [comment]
I think that in general we are not proposing any UX at all.  That is out of
scope.  Various user agents will likely step into this space, and
differentiate themselves on the quality of the user experience.

On Mon, Feb 29, 2016 at 8:32 AM, Jeff Burdges <notifications@github.com>
wrote:

> Just an aside, we know that shipping address cannot be divulged without
> user interaction, but presumably the amount of user interaction is quite
> significant, as people use numerous shipping addresses, and the option for
> these things are quite significant. We're therefore talking about something
> more than a browser pop up every time a person wants to submit a shipping
> address, yes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/28#issuecomment-190233076>.
>



-- 
Shane McCarron
Projects Manager, Spec-Ops

**Comment by rsolomakhin** [comment]
Shane is correct. UX is out of scope of the spec. My plan for Chrome is to let users select one of their addresses or enter a new address. Other user agents are likely to do the same.

**Comment by adrianba** [comment]
Now tracked by w3c/browser-payment-api#6.
