### ISSUE TITLE
Do we need to support transactions that aren't finalised by the merchant in v1?

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#3]
The proposal allows the payment instrument to return information that the merchant uses to complete the transaction or some kind of confirmation that a transaction has already been completed. Do we need to support the case of the UA completing the transaction independent of the merchant?

**Comment by zkoch** [comment]
I don't think so at this point. This is for a couple reasons:

1.) If anything, this should be handled by the Payment Instrument itself. But even then I'm not sure it's the right thing to do. I'm not a security expert, but it seems risky to trust the final execution of a payment to a process outside of your control.

2.) This would require inserting the UA between the Merchant and their respective payment processor. This is a really complicated space, and I think we'd have to look into standardizing this behavior for it to work successfully, which I think would be substantially more difficult than what is being proposed. I also think we would be pretty firmly opposed by the payment processors (as an example, see: https://lists.w3.org/Archives/Public/public-webpayments-ig/2015Sep/0121.html)

**Comment by adrianba** [comment]
I'm closing this issue. I asked a broad question early in the investigation of this proposal. I think we should wait and see if concrete problems emerge as we add more detail.
