### ISSUE TITLE
Should the Payment Request API only be available in a top-level browsing context?

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#30]
This question has been raised as part of the discussion in issue #9.

The spec for the [`PaymentRequest` constructor](https://wicg.github.io/paymentrequest/specs/paymentrequest.html#paymentrequest-constructor) currently states that if the API is not called from a [top-level browsing context](http://www.w3.org/TR/html5/browsers.html#top-level-browsing-context) then a `SecurityError` should be thrown. The goal of this step is to avoid iframes with potentially untrusted content from making a payment request that the user perceives is actually coming from the top-level page. For example, a well-known publication web site that inadvertently includes a malicious ad.

The problem with this approach is that there are common scenarios where a site may host trusted third party content (e.g. games) in an iframe where the trusted content should be allowed to make a payment request.

One proposal here is to introduce an new attribute (e.g. `payment`) onto the iframe element that gives permission for content to make payment requests. Since this is provided by the containing page they get to decide whether they trust the content.

Another issue here is that an iframe may contain content from the same origin as the top-level browsing context. We should probably permit this call to be made and only block cross-origin payment requests.

**Comment by zkoch** [comment]
Just to clarify a bit, I think the best way would be to re-use the existing "sandbox" attribute on iFrames, but define a new potential value for that attribute of "allow-payment".

**Comment by webpayments** [comment]
I would caution against doing anything in this group that has a dependency
on changing HTML5.

On Wed, Dec 9, 2015 at 1:50 PM, Zach Koch <notifications@github.com> wrote:

> Just to clarify a bit, I think the best way would be to re-use the
> existing "sandbox" attribute on iFrames, but define a new potential value
> for that attribute of "allow-payment".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/30#issuecomment-163371214>.
>



-- 
-Shane

**Comment by adrianba** [comment]
> I would caution against doing anything in this group that has a dependency
on changing HTML5.

We don't have to change HTML5. Anybody can write an [extension spec](http://www.w3.org/html/wg/wiki/ExtensionSpecifications).

**Comment by webpayments** [comment]
Yes, but such a spec then requires all of attendant W3C nonsense and
overhead.  While this isn't a stated requirement, it would be nice if our
phase 1 solution were implementable as a polyfill.  Browser support is
great, but backward compatibility is great too.

On Wed, Dec 9, 2015 at 2:19 PM, Ade Bateman <notifications@github.com>
wrote:

> I would caution against doing anything in this group that has a dependency
> on changing HTML5.
>
> We don't have to change HTML5. Anybody can write an extension spec
> <http://www.w3.org/html/wg/wiki/ExtensionSpecifications>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/30#issuecomment-163380797>.
>



-- 
-Shane

**Comment by adrianba** [comment]
You can't impose any of the security requirements with a polyfill.

**Comment by burdges** [comment]
It'll go very badly very quickly if third party content can interact with third party payment tools.  lol  

In fact, even the top-level context should not be able to learn what payment instruments the user supports before the user selects the appropriate one, which requires a secure context that cannot contact the merchant, but maybe that discussion belongs in anther issue.

**Comment by adrianhopebailie** [comment]
There is a prominent use case that would require third-parties to be able to call the API (with explicit permission from the top-level context). That is the case of merchants (the top-level context) who offload their processing to third-party PSPs (sub-context) without doing a complete redirect of the user's browser to the PSP's website. @mattsaxon and @mountainhippo can provide some more detail I'm sure.

i.e. We DO need a mechanism for the top-level website to provide explicit permission to 3rd parties to call the API.

I would recommend that we get some thoughts from WebAppSec on this. cc @hillbrad

> In fact, even the top-level context should not be able to learn what payment instruments the user supports before the user selects the appropriate one, which requires a secure context that cannot contact the merchant, but maybe that discussion belongs in anther issue.

:+1:  the calling website learns nothing about the status of the request until the user has selected a payment app and the app has returned a response. It's even possible that the website never knows what app was used if the payment method response is standardized and that is all that's returned.

This is all with one caveat. It will be very valuable for a website to check if its *own* payment app is installed. This would be enforced by the UA which knows the origin of the app publisher and only supports the use of this API function if the origin of the current browsing context is the same. Merchants and PSPs that publish apps to facilitate custom payment methods that incorporate features such as loyalty programs or coupons will need a way to tailor the user experience prior to issuing the payment request so they can encourage customers to login (so they can customize the payment request) or install the merchant's payment app.

@burdges - This is related to your comment here too: https://github.com/w3c/webpayments/issues/28#issuecomment-163893044

**Comment by hillbrad** [comment]
Hi, Adrian.  I think whether or not an API should be available in an iframe
boils down to the security properties of that API.  Do users need to be
able to definitively know what context it's being called in to use it
safely, and is the URL bar the only way to know this with certainty?  It
certainly seems there are valuable use cases for payments inside an iframe,
so perhaps it should be a design goal that it is safe to use without this
context, e.g. by providing some notification in other browser-controlled
UI.  (We knew there was value in working in an iframe for FIDO, so we aimed
to make the API safe to use by constraining it to be fairly strictly
origin-bound, but that approach may not be suitable for payments.)

There are also some other nuances here.  It should probably be "foreground
only" (in the active tab vs. a background tab) regardless of whether it is
in the top vs a nested browsing context, and it probably should at be OK to
activate it in an iframe that is part of a unit of related similar origin
browsing contexts (
https://html.spec.whatwg.org/multipage/browsers.html#unit-of-related-similar-origin-browsing-contexts)
with the top-level context, even if you do decide a top-level restriction
is necessary.

**Comment by mattsaxon** [comment]
> @mattsaxon and @mountainhippo can provide some more detail I'm sure.

The scenario that Adrian mention is absolutely a key scenario in use today and going forward. This is where the merchant wants to retain full control of the basket experience, but to delegate the checkout experience (or at least the payment part of it) to a 3rd party (on a separate domain). Today this is commonly done via 3 approaches; 1) Full page redirect 2) iFrame 3) Popup (lightbox).

You can see an example of the first approach here http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/w3c/webpayments/gh-pages/PaymentFlows/Card/PSPHosted-CardPayment-Current.pml

Approaches 2 & 3 have a similar flow but don't use a full page redirect.

**Comment by adrianba** [comment]
This is now tracked at w3c/browser-payment-api#2.
