### ISSUE TITLE
Should the web page be able to provide status information before calling complete()

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#32]
Once the user has accepted the payment request, the `state` of `PaymentRequest` moves to `accepted` and the Promise returned from `show()` is resolved. The web page is responsible for processing the `PaymentResponse` and then calling `complete()` with a success or failure value. During this time the user may be wondering about what is happening. Should we provide a mechanism for the web page to provide message text back to the user agent about what it is doing to show progress?

**Comment by webpayments** [comment]
Sure - optional of course.

On Wed, Dec 9, 2015 at 2:09 PM, Ade Bateman <notifications@github.com>
wrote:

> Once the user has accepted the payment request, the state of
> PaymentRequest moves to accepted and the Promise returned from show() is
> resolved. The web page is responsible for processing the PaymentResponse
> and then calling complete() with a success or failure value. During this
> time the user may be wondering about what is happening. Should we provide a
> mechanism for the web page to provide message text back to the user agent
> about what it is doing to show progress?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WICG/paymentrequest/issues/32>.
>



-- 
-Shane

**Comment by adrianba** [comment]
This is now tracked at w3c/browser-payment-api#5.
