### ISSUE TITLE
What is the format for payment method identifiers for distributed extensibility

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#34]
The Payment Method Identifiers spec calls out some open issues. Payment method identifiers are strings and need to support some form of distributed extensibility. Various options have been suggested:
* URLs
* Host names
* Reverse domain names
* Partial URLs

**Comment by adrianhopebailie** [comment]
:+1: for URLs

- Globally unique
- Can be minted by anyone
- Could point to a useful resource such as payment method documentation
- May be useful to tie a payment method to an origin at some point in future or use well-known URLs that are hosted at the origin of the payment method identifier
- etc

**Comment by ianbjacobs** [comment]
Personally, I would favor:

 * short strings for common methods, that are listed in the spec. The "formal" spec can list the "approved" ones and the Editor's draft can be updated easily for the "next ones to be approved but aren't yet." 

And

 * URIs. Furthermore, I think publishers of those URIs SHOULD make available information about the rules of the method at those URIs, and SHOULD NOT make available unrelated information at those URIs.

**Comment by adrianhopebailie** [comment]
> short strings for common methods, that are listed in the spec. The "formal" spec can list the "approved" ones and the Editor's draft can be updated easily for the "next ones to be approved but aren't yet."

I think this mixing of short strings and URIs will do more harm than good.

> I think publishers of those URIs SHOULD make available information about the rules of the method at those URIs, and SHOULD NOT make available unrelated information at those URIs.

:+1:

**Comment by adrianba** [comment]
Now tracked by w3c/browser-payment-api#11.
