### ISSUE TITLE
CurrencyAmount description has exponent sign wrong

### ISSUE THREAD

**Issue by agfor** [WICG/paymentrequest#39]
Compare [the description](https://github.com/WICG/paymentrequest/blob/gh-pages/specs/paymentrequest.html#L525-L527):

> A CurrencyAmount dictionary is used to supply monetary amounts with known precision using base-10. The value of the amount is mantissa * 10 ^ exponent. The following fields must be supplied for a CurrencyAmount to be valid:

to [the example given](https://github.com/WICG/paymentrequest/blob/gh-pages/specs/paymentrequest.html#L525-L527):

> The following example shows how to represent US$55.00.

```
EXAMPLE 6
{
  "currencyCode": "USD",
  "mantissa": 5500,
  "exponent": 2
}
```

If the value was mantissa * 10 ^ exponent, the value would be 550000 not 55.00.

**Comment by msporny** [comment]
> If the value was mantissa * 10 ^ exponent, the value would be 550000 not 55.00.

This is exactly the sort of issue I'm concerned about wrt. the use of mantissa and exponent, even the spec got it wrong. I expect Web developers to get it wrong too, and potentially request payment for the wrong amount of money.

**Comment by zkoch** [comment]
Yeah, good catch. I suppose that should probably be -2 in the example.

**Comment by agfor** [comment]
I think it's more intuitive to use a positive exponent and fix the spec to
match.

**Comment by adrianba** [comment]
Moved to strings in #44.
