### ISSUE TITLE
No mention of non-decimal currencies

### ISSUE THREAD

**Issue by agfor** [WICG/paymentrequest#40]
The [CurrencyAmount](http://wicg.github.io/paymentrequest/specs/paymentrequest.html#currencyamount) section doesn't mention [non-decimal currencies](https://en.wikipedia.org/wiki/Non-decimal_currency).

The correct behavior is probably to not use the sub-unit for Mauritania & Madagascar, and consider the Sovereign Military Order of Malta unsupported.

**Comment by nickjshearer** [comment]
Ignoring non-demical currencies, there are plenty of currencies that technical have decimals but they're not expressed in the majority of cases (JPY would be the example that comes to mind). It would tend to agree with you that it would be better to change the language from "MUST" to something else, indicating the decimal point may not be required for some currencies.

**Comment by adrianhopebailie** [comment]
The proposal that was accepted by the WG (https://github.com/w3c/webpayments/issues/57) did not intend for the decimal separator to be mandatory:
> * The value of the amount property MAY contain a single dot to denote separation of the fractional suffix from the rest of the amount.
* If present, the dot MUST NOT be the first character of the amount.

**Comment by adrianba** [comment]
Now tracked at w3c/browser-payment-api#14.
