### ISSUE TITLE
Spec references are all pretty outdated

### ISSUE THREAD

**Issue by domenic** [WICG/paymentrequest#57]
- DOM4 contains an out of date definition of EventTarget and event dispatch, and defines DOMException types when really this is the responsibility of Web IDL. Use https://dom.spec.whatwg.org/ instead.

- ECMA-262 has evolved significantly since the 2015 edition, including the definition of TypeError and some changes to how promises work. Use https://tc39.github.io/ecma262/ instead.

- Web IDL (note: not WebIDL) is now where exceptions are defined. Use https://heycam.github.io/webidl/ instead.

- HTML5 has changed its definitions of browsing contexts and no longer defines the term "global object" in the way you use it here. Task queuing has also changed a bit due to event loop changes. Use http://html.spec.whatwg.org/ instead and be sure to use settings objects instead of global objects. (See next point.)

- The Privileged Contexts spec has been renamed Secure Contexts and operates on settings objects instead of global objects. Use https://w3c.github.io/webappsec-secure-contexts/ instead.

**Comment by adrianba** [comment]
Now tracked at w3c/browser-payment-api#20.
