### ISSUE TITLE
Can we call out how this relates to other payment efforts?

### ISSUE THREAD

**Issue by chroby** [WICG/paymentrequest#6]
I.e. how close is this to navigator.mozPay? 

https://wiki.mozilla.org/WebAPI/WebPayment

**Comment by adrianba** [comment]
The proposal is intended to be independent of payment method. Can you explain how this will help the spec? The Web Payment WG is considering many different kinds of [payment flows](https://github.com/w3c/webpayments/wiki/Flows) and WG proposals will be considered against these. If there is something specific about, for example mozPay, that you'd like considered you might choose to write-up a flow diagram.

I'm closing this issue for now. Please re-open with any new information.
