### ISSUE TITLE
At the time complete() is called, your ability to say success (true) or failure (false) may depend on the payment method

### ISSUE THREAD

**Issue by adrianba** [WICG/paymentrequest#67]
I propose that we change the signature of complete() to take a string instead. This also reads on #54. The string would be payment method specific and could be "true", "false", or "unknown", for example.

**Comment by ianbjacobs** [comment]
( Just to note here we discussed this briefly at the FTF meeting:  https://www.w3.org/2016/02/24-wpwg-minutes#item11 )

**Comment by nickjshearer** [comment]
As per the minutes, I concur with this proposal.

**Comment by rsolomakhin** [comment]
I have no objections. We need to update http://wicg.github.io/paymentrequest/specs/basic-card-payment.html to specify the correct response codes.

**Comment by adrianba** [comment]
Now tracked at w3c/browser-payment-api#17.
