### ISSUE TITLE
Reconsider the need to include shipping in this spec

### ISSUE THREAD

**Issue by nelsonmenezes** [WICG/paymentrequest#8]
As evidenced in #2, rules for shipping addresses can be quite complex. In addition, a couple more scenarios that might not integrate well with the spec as-is, and that might be quite complex to solve:

- Multiple shipping addresses. E.g. on Amazon I perform a single payment, but different parts of my order can go to multiple addresses.
- Address data format: With so many formats and exceptions around the world, we'd only be able to standardise on two fields, "address" and "country". And even the "country" bit can be problematic.

For the purpose of getting a workable payment spec, maybe the concept of shipping address should be outside of scope? As a different spec that can later interact with this one?

**Comment by zkoch** [comment]
I think it's a very fair point and one that we should strongly weigh. The motivation for including shipping in the original spec is that, from a user pain point perspective, actually typing in your payment information is only one step of a very painful funnel. The other big part of that is typing in address information. That said, I agree that this could be a bit of a rat hole. I would be interested to hear more thoughts on this.

**Comment by mattsaxon** [comment]
One thing we do need to consider is that address (or at least billing address) is sometime a mandatory part of the payment message. In Europe in particular, it is mandated for card Issuers to support address validation and the merchant often wishes to use this facility (though it is optional for them) to either reduce fees they pay or to reduce risk. This is known as AVS checking and like CVC checking, we need to support this for card transactions. Additionally merchant sometime wish to only ship to the billing address to further reduce risk.

**Comment by nelsonmenezes** [comment]
@mattsaxon in that case the address information is a dependency of the payment instrument (a credit card, say). Also, it is not necessarily the same as the shipping address — notwithstanding what you say about some merchants only shipping to billing address, there are many that do not. I think that having any address at the top level of the spec is probably not a good idea. Within specific payment instruments, of course, it makes sense.

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------

----==_mimepart_5649cf01b4493_34e73fa3a678b2a033350ab
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

@mattsaxon in that case the address information is a dependency of the paym=
ent instrument (a credit card, say). Also, it is not necessarily the same a=
s the shipping address =E2=80=94 notwithstanding what you say about some me=
rchants only shipping to billing address, there are many that do not. I thi=
nk that having any address at the top level of the spec is probably not a g=
ood idea. Within specific payment instruments, of course, it makes sense.

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/8#issuecomment-157016003=

----==_mimepart_5649cf01b4493_34e73fa3a678b2a033350ab
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p><a href=3D"https://github.com/mattsaxon" class=3D"user-mention">@mattsax=
on</a> in that case the address information is a dependency of the payment =
instrument (a credit card, say). Also, it is not necessarily the same as th=
e shipping address =E2=80=94 notwithstanding what you say about some mercha=
nts only shipping to billing address, there are many that do not. I think t=
hat having any address at the top level of the spec is probably not a good =
idea. Within specific payment instruments, of course, it makes sense.</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">&mda=
sh;<br>Reply to this email directly or <a href=3D"https://github.com/WICG/p=
aymentrequest/issues/8#issuecomment-157016003">view it on GitHub</a>.<img a=
lt=3D"" height=3D"1" src=3D"https://github.com/notifications/beacon/APFrHFF=
wAJLUOK6ycVpW2dp_YEE2T1wRks5pGcaBgaJpZM4GH6C9.gif" width=3D"1" /></p>
<div itemscope itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope itemtype=3D"http://schema.org/ViewAction=
">
  <link itemprop=3D"url" href=3D"https://github.com/WICG/paymentrequest/iss=
ues/8#issuecomment-157016003"></link>
  <meta itemprop=3D"name" content=3D"View Issue"></meta>
</div>
<meta itemprop=3D"description" content=3D"View this Issue on GitHub"></meta>
</div>

----==_mimepart_5649cf01b4493_34e73fa3a678b2a033350ab--

**Comment by dlongley** [comment]
@nelsonmenezes,

I agree that directly integrating the shipping/billing information with the payment request at the top level is also not the way to go. It should either be a separate step or integrated somehow with the payment instrument (potentially both of these depending on the flow). Having it be part of a separate step would also help with flows that involve providing coupons, loyalty cards, or other "credentials" that may affect offerings (eg: final price in the payment request may depend on a variety of information submitted to the merchant).

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------

----==_mimepart_564a1ba8ac1cc_4a5a3fe464d4b2b8269449
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

@nelsonmenezes,

I agree that directly integrating the shipping/billing information with the payment request at the top level is also not the way to go. It should either be a separate step or integrated somehow with the payment instrument (potentially both of these depending on the flow). Having it be part of a separate step would also help with flows that involve providing coupons, loyalty cards, or other "credentials" that may affect offerings (eg: final price in the payment request may depend on a variety of information submitted to the merchant).

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/8#issuecomment-157122281
----==_mimepart_564a1ba8ac1cc_4a5a3fe464d4b2b8269449
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p><a href="https://github.com/nelsonmenezes" class="user-mention">@nelsonmenezes</a>,</p>

<p>I agree that directly integrating the shipping/billing information with the payment request at the top level is also not the way to go. It should either be a separate step or integrated somehow with the payment instrument (potentially both of these depending on the flow). Having it be part of a separate step would also help with flows that involve providing coupons, loyalty cards, or other "credentials" that may affect offerings (eg: final price in the payment request may depend on a variety of information submitted to the merchant).</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/8#issuecomment-157122281">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHLLfhzQ2NovpW0C14DFbLvg8eeuSks5pGhMogaJpZM4GH6C9.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/8#issuecomment-157122281"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_564a1ba8ac1cc_4a5a3fe464d4b2b8269449--

**Comment by mattsaxon** [comment]
@nelsonmenezes, @dlongley 

I agree with both of you, I just wanted to highlight that if we remove it from the top level (as is my expectation) then we need to allow for it for specific payment instruments.

**Comment by adrianba** [comment]
This issue has covered two topics:
* Whether to include shipping address given the complexities of defining an address type
* How to deal with billing address for scenarios like AVS checking

@rsolomakhin is going to make a proposal for address fields in issue #28.
I will make a proposal for how to incorporate this for billing address in a card payment method spec as part of issue #31.

Closing this issue and deferring the detailed topics to #28 and #31.
