### ISSUE TITLE
Chain of trust between browser and merchant

### ISSUE THREAD

**Issue by zkoch** [WICG/paymentrequest#9]
This is more of an open discussion point about how far we should go to establish a chain of trust between the merchant and the browser. Should there be a minimum set of criteria the merchant should meet security wise for the API to return payment instrument data?

A good starting point seems to be ensuring valid HTTPS (verified identity, modern cipher suite, etc). Is there more to do here?

**Comment by greenido** [comment]
I would just add few thoughts:
* Verified identity - Do we wish to have white list? black list? both?
* In many cases the merchant will have its own identity (e.g. https with a valid key), in these cases, the solution is 'easy'. However, what are we going to do for SMBs that don't have it but still wish to sell goods?
* HTTPS seems like a 'must have'.

**Comment by zkoch** [comment]
> Do we wish to have white list? black list? both?

Possibly. I would prefer to avoid a whitelist scenario, because this substantially slows down adoption and creates a huge barrier. A blacklist of known bad actors is a possibility, but it does raise the question of where such a blacklist would reside, who controls it, etc. Are there successful examples of this elsewhere? 

> However, what are we going to do for SMBs that don't have it but still wish to sell goods?

I think valid HTTP (i.e. a green lock icon in Chrome) is going to be a must-have, even for SMBs. I don't see a way around this and still maintain the integrity of the system.

**Comment by adrianba** [comment]
We need to think about the context that is calling the paymentRequest API. For example, if an iframe on a page from another origin makes a request we should probably not allow this.

**Comment by zkoch** [comment]
Agreed. I imagine we might run into issues for some sites that embed payment forms via iFrames from their PSPs, but not sure this can be avoided.

**Comment by adrianba** [comment]
This is a broad issue that covers several aspects of the Payment Request system:

* It covers security considerations about when and how the API can be consumed
  * Is the API only available in a secure context? This is covered in issue #29.
  * Is the API only available in a top-level browsing context? This is covered in issue #30.
* It covers the integrity of the PaymentResponse data that is returned by the payment method. There are options here for signing and encrypting some data but we think this is the domain of the specific payment method and we don't plan to make this a requirement for all methods (for example, returning simple card information including PAN and expiry won't have a need for signing/encryption).

Closing this broad issue now. We should open new issues for specific problems and continue the discussion about top-level browsing context in issue #30.
